name: Sync main back to dev

on:
  push:
    branches:
      - main

jobs:
  sync-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge main into dev
        run: |
          git fetch origin dev
          git checkout dev
          git merge origin/main --no-edit

      - name: Push changes to dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin dev
